In [5]:
import torch
import torch.nn as nn

In [6]:
x = torch.tensor([[1, 2, 3, 4], [5, 6, 7, 8]])
print(x)
print(x.shape)
print(x.unsqueeze(0))
print(x.unsqueeze(0).shape)
print(x.unsqueeze(1))
print(x.unsqueeze(1).shape)
print(x.unsqueeze(2))
print(x.unsqueeze(2).shape)

tensor([[1, 2, 3, 4],
        [5, 6, 7, 8]])
torch.Size([2, 4])
tensor([[[1, 2, 3, 4],
         [5, 6, 7, 8]]])
torch.Size([1, 2, 4])
tensor([[[1, 2, 3, 4]],

        [[5, 6, 7, 8]]])
torch.Size([2, 1, 4])
tensor([[[1],
         [2],
         [3],
         [4]],

        [[5],
         [6],
         [7],
         [8]]])
torch.Size([2, 4, 1])


In [7]:
m = nn.Softmax(dim = 1)
input = torch.randn(2, 3)
print(input)
print(input.shape)
output = m(input)
print(output)
print(output.shape)

r = input.sum(dim = 1)
print(r)
print(r.shape) # 맨 뒤 shape를 깜

tensor([[-1.4556, -2.1532, -1.5404],
        [-0.7184,  0.0173, -1.5527]])
torch.Size([2, 3])
tensor([[0.4138, 0.2060, 0.3802],
        [0.2840, 0.5927, 0.1233]])
torch.Size([2, 3])
tensor([-5.1492, -2.2539])
torch.Size([2])


In [8]:
input = torch.randn(2, 3, 4)
print(input.shape)
print(input)
input2 = torch.randn(2, 3)
print(input2.shape)
print(input2)
input2 = input2.unsqueeze(2)
print(input2.shape)
print(input2)
output = input * input2
print(output.shape)
print(output)
output = output.sum(dim = 1)
print(output.shape)
print(output)

torch.Size([2, 3, 4])
tensor([[[ 0.2881, -1.2104,  0.1285, -0.5789],
         [-0.7929,  0.9530,  1.7707,  0.2155],
         [-0.1454,  0.7611, -0.2382, -0.4353]],

        [[ 0.2724, -0.1085, -1.2954, -0.0536],
         [ 0.1782,  0.2330,  0.5830,  0.2024],
         [-0.0487,  0.0418,  0.1305, -0.4842]]])
torch.Size([2, 3])
tensor([[ 0.8680, -1.0080, -1.5043],
        [-0.7051, -0.8599, -0.6361]])
torch.Size([2, 3, 1])
tensor([[[ 0.8680],
         [-1.0080],
         [-1.5043]],

        [[-0.7051],
         [-0.8599],
         [-0.6361]]])
torch.Size([2, 3, 4])
tensor([[[ 0.2501, -1.0506,  0.1115, -0.5025],
         [ 0.7992, -0.9607, -1.7849, -0.2173],
         [ 0.2188, -1.1449,  0.3583,  0.6548]],

        [[-0.1921,  0.0765,  0.9133,  0.0378],
         [-0.1532, -0.2004, -0.5013, -0.1740],
         [ 0.0310, -0.0266, -0.0830,  0.3080]]])
torch.Size([2, 4])
tensor([[ 1.2681, -3.1561, -1.3152, -0.0649],
        [-0.3143, -0.1505,  0.3290,  0.1718]])
